version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: netflix-frontend
    ports:
      - "80:80"
    networks:
      - netflix-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: netflix-backend
    ports:
      - "8000:9000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./back-end:/var/www
    networks:
      - netflix-network
    env_file:
      - .env


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: netflex
      MYSQL_USER: bachlai
      MYSQL_PASSWORD: 12345678
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - netflix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:

networks:
  netflix-network:
    driver: bridge